export const projects = [
    {
        title: 'Junior: Grade Calculator [W.I.P.]',
        description: '2026',
        image: '',
        tags: ['Vite + React', 'TypeScript', 'Web'],
        github: 'https://github.com/JoshuaSubray/Junior',
        deployment: 'https://joshuasubray.github.io/Junior',
    },
    {
        title: 'SeeSharpReviews',
        description: '2026',
        image: '',
        tags: ['ASP.NET Core', 'C#', 'API'],
        github: 'https://github.com/JoshuaSubray/SeeSharpReviews',
        deployment: 'https://seesharpreviews.onrender.com',
    },
    {
        title: 'Care Compass',
        description: '2026',
        image: '',
        tags: ['Vite + React', 'TypeScript', 'Web'],
        github: 'https://github.com/lgxnders/Capstone-Project',
        deployment: 'https://care-compass-capstone.onrender.com',
    },
    {
        title: 'Birman Banking',
        description: '2025',
        image: '',
        tags: ['Vite + React', 'Spring', 'Web'],
        github: 'https://github.com/BeaVert16/Birman-Banking-CPAN-228-Frontend',
        deployment: 'https://birman-banking.onrender.com',
    },
    {
        title: 'Pype: Instant Messenger',
        description: '2025',
        image: '',
        tags: ['Flask', 'Python', 'Web'],
        github: 'https://github.com/JoshuaSubray/Pype',
        deployment: 'https://pype.onrender.com',
    },
    {
        title: 'JAJ: Car Wash',
        description: '2024',
        image: '',
        tags: ['Node.js', 'Pug', 'Web'],
        github: 'https://github.com/JoshuaSubray/JAJ-Car-Wash',
        deployment: 'https://jaj-car-wash.onrender.com',
    },
    {
        title: 'JAJ: Currency Exchange',
        description: '2024',
        image: '',
        tags: ['React Native', 'API', 'Mobile'],
        github: 'https://github.com/JoshuaSubray/JAJ-Currency-Exchange',
        deployment: 'https://jaj-currency-exchange.onrender.com',
    },
    {
        title: 'JJ: Currency Exchange',
        description: '2024',
        image: '',
        tags: ['React', 'API', 'Web'],
        github: 'https://github.com/JoshuaSubray/JJ-Currency-Exchange',
        deployment: 'https://joshuasubray.github.io/JJ-Currency-Exchange',
    },
    {
        title: 'Space Observatory',
        description: '2023',
        image: '',
        tags: ['HTML', 'CSS', 'JavaScript'],
        github: 'https://github.com/JoshuaSubray/Space-Observatory',
        deployment: 'https://joshuasubray.github.io/Space-Observatory'
    }
]
